import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom';
import api from './services/api';
import './portal.css';

type User = {id:string; name:string; email:string; role:'tier1_supplier'|'tier2plus_supplier'};
type RequestRow = {id:string; productName:string; description?:string; deadline:string; status:string; functionalUnit?:string; tier2plusSupplier?:User; tier1Supplier?:User};
type Feedback = {id:string; type:string; content:string; createdAt:string};
type DocumentRow = {id:string; productName:string; status:string; createdAt:string; uploadRequestId:string; supplier?:User; fileName?:string; fileHash?:string; inventoryData?:object; feedbacks?:Feedback[]};
const labels:Record<string,string> = {pending:'요청 대기',in_progress:'검토 진행',completed:'완료',cancelled:'취소',submitted:'제출 완료',reviewed:'검토 중',approved:'승인',rejected:'보완 요청',comment:'검토 의견',approval:'승인',rejection:'보완 요청',not_registered:'미등록',verified:'등록 해시 일치',changed:'자료 변경 감지',mismatch:'등록 기록 불일치',confirmation_required:'거래 결과 확인 필요'};
const date = (s:string) => new Date(s).toLocaleDateString('ko-KR');
const message = (e:unknown) => { const x=e as {response?:{data?:{message?:string|string[]}}}; const m=x.response?.data?.message; return Array.isArray(m)?m.join(', '):m || '처리하지 못했습니다. 연결 상태와 입력 내용을 확인하고 다시 시도해 주세요.'; };
function Badge({status}:{status:string}) {return <span className={`badge ${status}`}>{labels[status] || status}</span>}
function Portal() {
 const navigate=useNavigate(), location=useLocation();
 const [user,setUser]=useState<User|null>(null), [ready,setReady]=useState(false);
 const [requests,setRequests]=useState<RequestRow[]>([]), [docs,setDocs]=useState<DocumentRow[]>([]), [suppliers,setSuppliers]=useState<User[]>([]);
 const [loading,setLoading]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState(''), [notice,setNotice]=useState('');
 const [modal,setModal]=useState<'request'|'upload'|'detail'|null>(null), [request,setRequest]=useState<RequestRow|null>(null), [doc,setDoc]=useState<DocumentRow|null>(null);
 const [search,setSearch]=useState(''), [filter,setFilter]=useState('all'), [review,setReview]=useState('comment'), [proof,setProof]=useState(''), [consent,setConsent]=useState(false), [hedera,setHedera]=useState(false);
 const [preview,setPreview]=useState('');
 const [email,setEmail]=useState(''), [password,setPassword]=useState('');
 const tier1=user?.role==='tier1_supplier'; const section=location.pathname.split('/').pop() || 'dashboard';
 const demo=import.meta.env.VITE_DEMO === 'true';
 const logout=()=>{localStorage.removeItem('token');setUser(null);setRequests([]);setDocs([]);setModal(null);setError('');setNotice('');navigate('/login');};
 async function load() { setLoading(true);setError('');try {const [r,d]=await Promise.all([api.get('/upload-requests'),api.get('/lca-data')]);setRequests(r.data);setDocs(d.data);if(user?.role==='tier1_supplier')setSuppliers((await api.get('/users/sub-suppliers')).data);}catch(e){setError(message(e));}finally{setLoading(false);} }
 useEffect(()=>{async function restore(){try{if(localStorage.getItem('token'))setUser((await api.get('/users/me')).data);}catch{localStorage.removeItem('token');}finally{setReady(true);}}void restore();void api.get('/health').then(r=>setHedera(r.data.hederaEnabled===true)).catch(()=>{});},[]);
 useEffect(()=>{if(user){void load();if(location.pathname==='/login'||location.pathname==='/')navigate(`/${user.role==='tier1_supplier'?'tier1':'tier2'}/dashboard`,{replace:true});}},[user]);
 useEffect(()=>{setSearch('');setFilter('all');},[location.pathname]);
 useEffect(()=>{if(!modal)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setModal(null);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[modal,busy]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api.post('/auth/login',{email,password});localStorage.setItem('token',r.data.access_token);setUser(r.data.user);setPassword('');navigate(`/${r.data.user.role==='tier1_supplier'?'tier1':'tier2'}/dashboard`);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function action(fn:()=>Promise<unknown>, success:string){setBusy(true);setError('');try{await fn();setNotice(success);setModal(null);await load();}catch(e){setError(message(e));}finally{setBusy(false);}}
 function openUpload(r:RequestRow){setRequest(r);setError('');setModal('upload');}
 async function openDetail(d:DocumentRow){setDoc(d);setReview('comment');setProof('');setPreview('');setConsent(false);setError('');setModal('detail');try{const r=await api.get(`/lca-data/${d.id}`);setDoc(r.data);}catch(e){setError(message(e));}}
 async function previewFile(d:DocumentRow){try{const r=await api.get(`/lca-data/${d.id}/file`,{responseType:'text'});setPreview(String(r.data).slice(0,20000));}catch(e){setError(message(e));}}
 async function download(d:DocumentRow){try{const r=await api.get(`/lca-data/${d.id}/file`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=d.fileName||'evidence';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(message(e));}}
 async function anchor(publish:boolean){if(!doc)return;setBusy(true);setError('');try{const r=publish?await api.post(`/lca-data/${doc.id}/anchor`,{publishHash:true}):await api.get(`/lca-data/${doc.id}/anchor`);setProof(r.data.status==='submitted'?'등록 영수증 수신 · 네트워크 조회 필요':r.data.status==='pending'?'네트워크 반영 대기':labels[r.data.status]||r.data.status);}catch(e){setError(message(e));}finally{setBusy(false);}}
 if(!ready)return <div className="loading">작업 공간을 준비하고 있습니다…</div>;
 if(!user)return <main className="login-shell"><section className="login-story"><div className="wordmark">◈ TRACE</div><p className="eyebrow">SUPPLY CHAIN EVIDENCE</p><h1>공급망의 데이터,<br/>신뢰할 수 있는 기록으로.</h1><p>자료 요청부터 제출, 검토와 이력 확인까지.<br/>협력사의 환경 데이터를 하나의 흐름으로 연결합니다.</p><div className="story-flow"><span>01 요청</span><span>02 제출</span><span>03 검토</span></div><small>KAIST Application Program · Portfolio</small></section><section className="login-form"><p className="eyebrow">WELCOME BACK</p><h2>작업 공간 로그인</h2><p className="muted">계정에 따라 요청자 또는 제출자 화면으로 연결됩니다.</p>{demo&&<div className="demo-box"><strong>로컬 포트폴리오 시연</strong><p>아래 계정으로 두 역할을 확인할 수 있습니다. 실제 기업 데이터가 아닙니다.</p><div className="button-row"><button type="button" onClick={()=>{setEmail('tier1@test.com');setPassword('password123');}}>요청자 계정 입력</button><button type="button" onClick={()=>{setEmail('tier2@test.com');setPassword('password123');}}>제출자 계정 입력</button></div></div>}<form onSubmit={login}><label>이메일<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>비밀번호<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={busy}>{busy?'확인 중…':'로그인'}</button></form><p className="footnote">LCA 자료 관리 시연 · 자동 탄소 산정이나 환경 인증을 제공하지 않습니다.</p></section></main>;
 const nav=[{key:'dashboard',name:'업무 현황',icon:'◫'},{key:'requests',name:tier1?'자료 요청':'받은 요청',icon:'↗'},{key:'data',name:tier1?'자료 검토':'제출 이력',icon:'▤'}];
 const rRows=requests.filter(r=>r.productName.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||r.status===filter));
 const dRows=docs.filter(d=>d.productName.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||d.status===filter));
 const pending=docs.filter(d=>['submitted','reviewed'].includes(d.status)).length;
 const active=(r:RequestRow)=>docs.some(d=>d.uploadRequestId===r.id&&['submitted','reviewed','approved'].includes(d.status));
 return <div className="workspace"><aside className="sidebar"><div className="wordmark">◈ TRACE</div><p className="sidebar-caption">공급망 증빙 관리</p><nav>{nav.map(n=><button key={n.key} className={section===n.key?'selected':''} onClick={()=>navigate(`/${tier1?'tier1':'tier2'}/${n.key}`)}><span>{n.icon}</span>{n.name}</button>)}</nav><div className="account"><div className="avatar">{user.name.slice(0,1)}</div><strong>{user.name}</strong><small>{tier1?'1차 협력사 · 요청 및 검토':'2차 협력사 · 자료 제출'}</small><button onClick={logout}>로그아웃 / 계정 전환</button></div></aside><div className="main-column"><header className="topbar"><span>{tier1?'요청자 작업 공간':'제출자 작업 공간'}</span><span className="environment">{demo?'● 로컬 시연':'● 연결됨'}</span></header><main className="content"><div className="page-heading"><div><p className="eyebrow">{section==='dashboard'?'OVERVIEW':section==='requests'?'REQUESTS':'EVIDENCE'}</p><h1>{nav.find(n=>n.key===section)?.name||'업무 현황'}</h1><p className="muted">{tier1?'협력사의 자료를 요청하고, 근거를 확인한 뒤 검토 결과를 남기세요.':'받은 요청을 확인하고 자료를 제출하세요. 보완 의견과 승인 결과가 이력에 남습니다.'}</p></div><div className="button-row"><button onClick={()=>void load()} disabled={loading}>새로고침</button>{tier1&&<button className="primary" onClick={()=>{setError('');setModal('request');}}>+ 자료 요청</button>}</div></div>{notice&&<div role="status" className="notice">{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}>×</button></div>}{error&&!modal&&<div role="alert" className="error">{error}</div>}{loading&&<p role="status" className="muted">최신 자료를 불러오는 중…</p>}
 {section==='dashboard'&&<><div className="metrics"><article><p>전체 요청</p><strong>{requests.length}</strong><small>협력사와 연결된 요청</small></article><article><p>검토 대기</p><strong>{pending}</strong><small>제출 완료 및 검토 중</small></article><article><p>승인 완료</p><strong>{docs.filter(d=>d.status==='approved').length}</strong><small>검토자가 확인한 자료</small></article><article><p>보완 요청 이력</p><strong>{docs.filter(d=>d.status==='rejected').length}</strong><small>재제출 이전 기록 포함</small></article></div><section className="workflow"><div><p className="eyebrow">YOUR NEXT STEP</p><h2>{tier1?'근거를 확인하고 다음 단계로.':'요청 조건에 맞춰 자료를 준비하세요.'}</h2><p>{tier1?'자료 검토에서 원문을 내려받고 승인 또는 보완 의견을 남길 수 있습니다.':'CSV, Excel, JSON 파일 또는 구조화된 JSON 데이터로 제출할 수 있습니다.'}</p><button className="primary" onClick={()=>navigate(`/${tier1?'tier1/data':'tier2/requests'}`)}>{tier1?'자료 검토하기':'받은 요청 확인'} →</button></div><ol><li>요청 조건 확인</li><li>증빙 자료 제출</li><li>검토 및 보완</li><li>승인 이력 보관</li></ol></section><section className="panel"><div className="panel-heading"><h2>최근 활동</h2><span className="muted">실제 저장된 자료 기준</span></div>{docs.length?docs.slice(0,5).map(d=><button className="activity" key={d.id} onClick={()=>void openDetail(d)}><span className="file-icon">▤</span><span><strong>{d.productName}</strong><small>{d.fileName||'구조화된 데이터'} · {date(d.createdAt)}</small></span><Badge status={d.status}/><span>→</span></button>):<div className="empty"><h3>첫 자료를 기다리고 있습니다</h3><p>요청과 제출이 시작되면 이곳에서 최근 활동을 확인할 수 있습니다.</p></div>}</section></>}
 {section!=='dashboard'&&<section className="panel"><div className="toolbar"><input aria-label="제품명 검색" placeholder="제품명으로 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">모든 상태</option>{(section==='requests'?['pending','in_progress','completed','cancelled']:['submitted','reviewed','approved','rejected']).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>제품 / 자료</th><th>{section==='requests'?'협력사':'제출일'}</th><th>{section==='requests'?'마감일':'자료 형태'}</th><th>상태</th><th>작업</th></tr></thead><tbody>{section==='requests'?rRows.map(r=><tr key={r.id}><td><strong>{r.productName}</strong><small>{r.description||'요청 설명 없음'}{r.functionalUnit&&` · ${r.functionalUnit}`}</small></td><td>{(tier1?r.tier2plusSupplier:r.tier1Supplier)?.name||'협력사'}</td><td>{date(r.deadline)}</td><td><Badge status={r.status}/></td><td>{!tier1&&!['completed','cancelled'].includes(r.status)&&!active(r)?<button onClick={()=>openUpload(r)}>자료 제출</button>:<button onClick={()=>{navigate(`/${tier1?'tier1':'tier2'}/data`);}}>제출 이력</button>}</td></tr>):dRows.map(d=><tr key={d.id}><td><strong>{d.productName}</strong><small>{d.supplier?.name||user.name}</small></td><td>{date(d.createdAt)}</td><td>{d.fileName||'JSON 데이터'}</td><td><Badge status={d.status}/></td><td><button onClick={()=>void openDetail(d)}>{tier1?'자료 검토':'상세 / 피드백'}</button></td></tr>)}</tbody></table></div>{(section==='requests'?rRows:dRows).length===0&&<div className="empty"><h3>표시할 자료가 없습니다</h3><p>{search||filter!=='all'?'검색어와 필터를 변경해 보세요.':tier1?'새 자료 요청을 만들어 업무를 시작하세요.':'요청자가 자료 요청을 생성하면 여기에 표시됩니다.'}</p></div>}</section>}
 <footer>TRACE · 공급망 자료 관리 <span>원문 수집과 검토 이력을 연결합니다.</span></footer></main></div>
 {modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="modal-heading"><div><p className="eyebrow">{modal==='request'?'NEW REQUEST':modal==='upload'?'SUBMIT EVIDENCE':'REVIEW EVIDENCE'}</p><h2 id="dialog-title">{modal==='request'?'자료 요청 만들기':modal==='upload'?'자료 제출':doc?.productName}</h2></div><button aria-label="창 닫기" disabled={busy} onClick={()=>setModal(null)}>×</button></div>{error&&<div role="alert" className="error">{error}</div>}
 {modal==='request'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>api.post('/upload-requests',{tier2plusSupplierId:f.get('supplier'),productName:f.get('product'),description:f.get('description'),deadline:new Date(String(f.get('deadline'))+'T23:59:59').toISOString(),functionalUnit:f.get('unit'),priority:f.get('priority')}),'자료 요청을 보냈습니다. 제출자 계정에서 확인할 수 있습니다.');}}><label>제품명<input name="product" required maxLength={150} autoFocus placeholder="예: 재생 알루미늄 하우징"/></label><label>제출 협력사<select name="supplier" required><option value="">협력사 선택</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="form-grid"><label>제출 마감일<input type="date" name="deadline" required min={new Date().toLocaleDateString('en-CA')}/></label><label>우선순위<select name="priority"><option value="medium">보통</option><option value="high">높음</option><option value="low">낮음</option></select></label></div><label>기능 단위<input name="unit" placeholder="예: 제품 1개"/></label><label>요청 내용<textarea name="description" rows={3} placeholder="필요한 자료와 검토 기준을 입력하세요."/></label>{!suppliers.length&&<p className="error">연결된 제출 협력사가 없습니다. 시연 계정 초기화를 확인하세요.</p>}<button className="primary full" disabled={busy||!suppliers.length}>{busy?'저장 중…':'요청 보내기'}</button></form>}
 {modal==='upload'&&request&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const file=f.get('file') as File;const json=String(f.get('json')||'').trim();let parsed:unknown;try{if(json){parsed=JSON.parse(json);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();}if(!file?.size&&!json){setError('파일 또는 JSON 데이터를 입력해 주세요.');return;}if(file?.size>10*1024*1024){setError('파일은 10MB까지 제출할 수 있습니다.');return;}}catch{setError('JSON은 올바른 객체 형식으로 입력해 주세요.');return;}const body=new FormData();body.set('productName',request.productName);body.set('uploadRequestId',request.id);if(file?.size)body.set('file',file);if(parsed)body.set('inventoryData',JSON.stringify(parsed));body.set('functionalUnit',request.functionalUnit||'');void action(()=>api.post('/lca-data/upload',body,{headers:{'Content-Type':'multipart/form-data'}}),'자료를 제출했습니다. 검토 결과는 제출 이력에서 확인하세요.');}}><div className="summary-box"><strong>{request.productName}</strong><p>{request.description||'요청 조건에 맞춰 자료를 제출해 주세요.'}</p><small>마감 {date(request.deadline)} · {request.functionalUnit||'기능 단위 미지정'}</small></div><label>증빙 파일<input type="file" name="file" accept=".csv,.xlsx,.xls,.json"/></label><p className="muted">CSV · Excel · JSON / 최대 10MB</p><label>구조화된 데이터 (선택)<textarea name="json" rows={5} placeholder={'{\n  "electricity_kwh": 125,\n  "material_kg": 40\n}'}/></label><p className="footnote">제출 자료는 검토 이력 보존을 위해 수정하지 않습니다. 보완 요청을 받으면 새 자료로 다시 제출할 수 있습니다.</p><button className="primary full" disabled={busy}>{busy?'제출 중…':'자료 제출하기'}</button></form>}
 {modal==='detail'&&doc&&<><div className="detail-meta"><Badge status={doc.status}/><span>{date(doc.createdAt)} 제출</span></div>{doc.fileName&&<div className="file-card"><span>▤ {doc.fileName}</span><div className="button-row">{/\.(csv|json)$/i.test(doc.fileName)&&<button onClick={()=>void previewFile(doc)}>원문 미리보기</button>}<button onClick={()=>void download(doc)}>원문 다운로드</button></div></div>}{preview&&<details open><summary>원문 미리보기 (최대 20,000자)</summary><pre>{preview}</pre></details>}{doc.inventoryData&&<details open><summary>제출 데이터</summary><pre>{JSON.stringify(doc.inventoryData,null,2)}</pre></details>}<h3>검토 이력</h3>{doc.feedbacks?.length?doc.feedbacks.map(f=><article className="feedback" key={f.id}><Badge status={f.type}/><small>{date(f.createdAt)}</small><p>{f.content}</p></article>):<p className="muted">아직 검토 의견이 없습니다.</p>}{tier1&&['submitted','reviewed'].includes(doc.status)&&<form className="review-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>api.post('/feedback',{lcaDataId:doc.id,type:review,content:f.get('content')}),'검토 결과를 저장했습니다. 협력사도 같은 이력을 확인할 수 있습니다.');}}><label>검토 결과<select value={review} onChange={e=>setReview(e.target.value)}><option value="comment">검토 의견</option><option value="approval">승인</option><option value="rejection">보완 요청</option></select></label><label>검토 의견<textarea name="content" required rows={3} placeholder="확인한 근거 또는 보완할 내용을 남겨 주세요."/></label><button className="primary full" disabled={busy}>검토 결과 저장</button></form>}{!tier1&&doc.status==='rejected'&&<button className="primary" onClick={()=>{const r=requests.find(r=>r.id===doc.uploadRequestId);if(r)openUpload(r);}}>보완 자료 재제출</button>}<section className="integrity"><h3>문서 무결성 확인</h3><p>현재 자료의 해시를 Hedera testnet 기록과 비교합니다. 환경 수치의 정확성을 인증하지 않습니다.</p>{!hedera?<p className="muted">이 시연에서는 외부 네트워크 등록을 사용하지 않습니다. 실제 키를 설정한 환경에서만 등록할 수 있습니다.</p>:<>{proof&&<p role="status"><strong>{proof}</strong></p>}<button disabled={busy} onClick={()=>void anchor(false)}>등록 상태 조회</button>{tier1&&doc.status==='approved'&&<><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>자료 해시의 공개 testnet 등록에 동의합니다.</label><button disabled={busy||!consent} onClick={()=>void anchor(true)}>해시 등록</button></>}</>}{doc.fileHash&&<details><summary>파일 SHA-256</summary><code>{doc.fileHash}</code></details>}</section></>}
 </section></div>}
 </div>;
}
export default function App(){return <BrowserRouter><Portal/></BrowserRouter>}
